Pratik/recommendations
Shivz3232/inovact-nodejs-veyga pull request #109
Opened 2024-06-13 14:53 UTC by C0SMlC

2024-06-15 15:05 UTC, Shivz3232 requested changes

2024-06-15 15:05 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/tokenizer.js
> +  const tokenizer = new natural.WordTokenizer();
Initialize the tokenizer outside the function block to avoid repetitively initializing the class

2024-06-15 15:05 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/stopWords.js
> +  const stopWords = new Set(natural.stopwords);
Initialize the list of stop words outside the function block

2024-06-15 15:05 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/stemming.js
> +  const stemmer = natural.PorterStemmer;
initialize stemmer outside

2024-06-15 15:05 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/index.js
> +    .replace(/[^\w\s]/g, '')
remove digits too

2024-06-15 15:05 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/index.js
> +  tokens = lemmatize(tokens);
My bad, we have to do either lemmatization or stemming & not both. Let's use Lemmatization in our case. You can lookup lemmatizing vs stemming for more info

2024-06-15 15:05 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/index.js
> +  tokens = lemmatize(tokens);
Keep the stemming util, just remove it from the index

2024-06-15 15:05 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/lemmatizer.js
> +  return tokens.map((token) => lemmatizer.noun(token) || lemmatizer.verb(token) || lemmatizer.adjective(token) || token);
Can we try to lemmatize in place instead of creating a new array & returning it?

2024-06-21 16:23 UTC, Shivz3232 requested changes

2024-06-21 16:23 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/queries/queries.js
> +  project(where: {
We can include projects within user bloc, that will automatically provide only the users projects.
```
user {
  user_skills
  user_interests
  projects {
    ...
    project_tags {
      ...
    }
  }
}
```

2024-06-21 16:23 UTC, Shivz3232 commented on src/utils/recommendations/preprocessing/stemming.js
> +  return tokens.map((token) => stemmer.stem(token));
Process in place instead of creating a new array

2024-06-23 06:18 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/vectorBasedMapping.js
> +  documentVectorModulus = Math.sqrt(documentVectorModulus);
Move this check to the beginning to skip other computations when true

2024-06-23 06:18 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/vectorBasedMapping.js
> +  if (documentVectorModulus === 0) {
Move this check to the beginning to skip other computations when true

2024-06-23 06:21 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/index.js
> +    const profile = await createProjectProfile(projects[i]); // Parallelize
Use Promise.all to calculate project profiles parallely

2024-06-23 06:22 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/index.js
> +    const profile = await createProjectProfile(projects[i]); // Parallelize
My bad, createProjectProfile isn't an async function, lets remove await & see how we can parallelize

2024-06-23 06:25 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/index.js
> +  const projectProfiles = new Map();
As the profile is actually inside the value of the map (144, { profile }), think of a better naming scheme for `userProfile` & `projectProfiles` variables.

2024-06-23 06:26 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/index.js
> +  // projectProfilesSortedByScore.forEach((projectProfile) => {
Remove comments

2024-06-23 06:29 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/vectorBasedMapping.js
Can we move this to utils, since the vector format will remain the same for other recommenders?

2024-06-23 06:30 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/recommender/userProfile.js
Can we move this to util? Will the user profile remain the same for all recommendations?

2024-06-23 06:31 UTC, Shivz3232 commented on src/controllers/project.controller/getProject/index.js
> +  return res.json(recommendedProjects);
@todo pagination

2024-06-25 16:06 UTC, C0SMlC commented on src/controllers/project.controller/getProject/recommender/userProfile.js
Yes, since the parameter for user profile remains same irrespective of the type of post

2024-06-25 17:33 UTC, merged