added the projects , ideas and thoughts controllers
Shivz3232/inovact-nodejs-veyga pull request #2
Opened 2022-05-08 06:09 UTC by khushilms-cs19

2022-05-08 07:12 UTC, Shivz3232 commented
Hey, I have added 2 comments on the idea router. Can you please resolve these on the idea router as well as other routers (post & thoughts)?

2022-05-08 07:48 UTC, Shivz3232 requested changes

2022-05-08 07:48 UTC, Shivz3232 commented on src/routes/v1/idea.route.js
> +    .get(ideaController.getIdeaPosts);
Can you please use the existing naming convention here?

2022-05-08 07:48 UTC, Shivz3232 commented on src/routes/v1/idea.route.js
> +const ideaController = require('../../controllers/ideas.controller/index');
You can omit the `/index`

2022-05-10 11:41 UTC, khushilms-cs19 commented
Hi shivu, i have added the controllers for add connection, reject connection and accept connection. Can you please check if it is right?

2022-05-13 18:02 UTC, closed without merging

2022-05-13 18:03 UTC, Shivz3232 commented
Closing PR, to open a new one from the newly created branch.